server:
  port: 8081
  servlet:
    context-path: /geek-template

spring:
  # 应用
  application:
    name: geek-template
  # 数据源
  datasource:
    name: geek
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/geek?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 最小空闲链接数
      minimumIdle: 5
      # 最大链接数
      maximumPoolSize: 50
      # 最大生命周期
      maxLifetime: 180000
      # 最长闲置时间
      idleTimeout: 60000
      # 等待连接池的最大毫秒数
      connectionTimeout: 20000

# mybatis-plus
mybatis-plus:
  # 对应的映射文件路径
  mapper-locations: classpath:mapper/*.xml
  # 对应的实体类
  type-aliases-package: com.geek.model.entity
  configuration:
    map-underscore-to-camel-case: true

# 日志
logging:
  level:
    com.geek.web.config.WebLogConfig: debug